#this code was adapted from Youtube
#https://www.youtube.com/watch?v=K9w01h4-Wnc
#goobar
#https://www.youtube.com/@goobar

name: Android Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set Up JDK
        uses: actions/setup-java@v3.13.0


      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew build

