#this code was adapted from Youtube
#https://www.youtube.com/watch?v=K9w01h4-Wnc
#goobar
#https://www.youtube.com/@goobar

name: Android Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Grant execution permission for tests
        run: chmod +x ./app/src/test/java/com/example/amigo/ExampleUnitTest.kt

      - name: Run Tests
        run: app/src/test/java/com/example/amigo/ExampleUnitTest.kt

      - name: Build Project
        run: ./gradlew assemble

